spring:
  application:
    name: template-webapi-server
  profiles:
    active: dev


 #hystrix.command.default.execution.timeout.enabled=false  关闭超时管理
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 80000

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
  

  

